### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by cavefxa** [dhondta/webgrep#5]
Upon installing the script and running on WSL.
Installation:
```bash
cave@DESKTOP-363NGJI:~$ sudo pip install webgrep-tool
```

Upon running:
```bash
cave@DESKTOP-363NGJI:~$ webgrep -R Welcome https://www.github.com
09:01:29 [WARNING] Binary required for applying steganography on images ;
 consider running 'sudo apt-get install steghide'
09:01:29 [WARNING] Binary required for trying OCR on images ;
 consider running 'sudo apt-get install tesseract-ocr'

09:01:34 [ERROR] Unexpected error: Invalid URL 'https:/': No host supplied
Traceback (most recent call last):
  File "/usr/local/bin/webgrep", line 771, in <module>
    page.grep().handle()
  File "/usr/local/bin/webgrep", line 568, in handle
    with Resource(url, self) as res:
  File "/usr/local/bin/webgrep", line 396, in __enter__
    return self._load()
  File "/usr/local/bin/webgrep", line 425, in _load
    return self.download()
  File "/usr/local/bin/webgrep", line 461, in download
    req = requests.Request('GET', self.url, headers=self.headers).prepare()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 257, in prepare
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'https:/': No host supplied
```

Environment:
```bash
cave@DESKTOP-363NGJI:~$ uname -a
Linux DESKTOP-363NGJI 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dhondta** [comment]
Hi @cavetownie !

Thanks for the heads up. I could find the bug. This should be fixed now.
Please `pip install --upgrade webgrep-tool` (to version 1.16).
